name: movie_moka
description: mobile application for reserve movie at cimahi

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^6.5.1
  intl: ^0.18.1
  provider: ^6.0.3
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  package_info_plus: ^3.0.2
  quiver: ^3.1.0
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svg/
